// resources/js/Pages/StockMovements/Create.jsx
import { Head, useForm } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import TextInput from '@/Components/TextInput';
import TextArea from '@/Components/TextArea';

export default function Create({ auth, products, product_id }) {
    const { data, setData, post, processing, errors, reset } = useForm({
        product_id: product_id || '',
        type: 'in',
        quantity: '',
        notes: '',
    });

    const submit = (e) => {
        e.preventDefault();
        post(route('stock-movements.store'), {
            onSuccess: () => reset(),
        });
    };

    return (
        <AuthenticatedLayout
            user={auth.user}
            header={<h2 className="font-semibold text-xl text-gray-800 leading-tight">New Stock Movement</h2>}
        >
            <Head title="New Stock Movement" />

            <div className="py-12">
                <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                    <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                        <div className="p-6 text-gray-900">
                            <form onSubmit={submit} className="space-y-6">
                                <div>
                                    <InputLabel htmlFor="product_id" value="Product" />
                                    <select
                                        id="product_id"
                                        name="product_id"
                                        value={data.product_id}
                                        className="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"
                                        onChange={(e) => setData('product_id', e.target.value)}
                                    >
                                        <option value="">Select a product</option>
                                        {products.map((product) => (
                                            <option key={product.id} value={product.id}>
                                                {product.name} (Current Stock: {product.stock})
                                            </option>
                                        ))}
                                    </select>
                                    <InputError message={errors.product_id} className="mt-2" />
                                </div>

                                <div>
                                    <InputLabel htmlFor="type" value="Movement Type" />
                                    <select
                                        id="type"
                                        name="type"
                                        value={data.type}
                                        className="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"
                                        onChange={(e) => setData('type', e.target.value)}
                                    >
                                        <option value="in">Stock In</option>
                                        <option value="out">Stock Out</option>
                                    </select>
                                    <InputError message={errors.type} className="mt-2" />
                                </div>

                                <div>
                                    <InputLabel htmlFor="quantity" value="Quantity" />
                                    <TextInput
                                        id="quantity"
                                        type="number"
                                        name="quantity"
                                        value={data.quantity}
                                        className="mt-1 block w-full"
                                        min="1"
                                        onChange={(e) => setData('quantity', e.target.value)}
                                    />
                                    <InputError message={errors.quantity} className="mt-2" />
                                </div>

                                <div>
                                    <InputLabel htmlFor="notes" value="Notes" />
                                    <TextArea
                                        id="notes"
                                        name="notes"
                                        value={data.notes}
                                        className="mt-1 block w-full"
                                        onChange={(e) => setData('notes', e.target.value)}
                                    />
                                    <InputError message={errors.notes} className="mt-2" />
                                </div>

                                <div className="flex items-center justify-end">
                                    <PrimaryButton className="ml-4" disabled={processing}>
                                        Record Movement
                                    </PrimaryButton>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}

// resources/js/Pages/StockMovements/Create.vue
<template>
  <AppLayout title="Record Stock Movement">
    <template #header>
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">Record Stock Movement</h2>
    </template>

    <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
          <form @submit.prevent="submit" class="p-6">
            <div class="max-w-xl space-y-6">
              <div>
                <label for="product_id" class="form-label">Product</label>
                <select
                  id="product_id"
                  v-model="form.product_id"
                  class="select-field"
                  :class="{ 'border-red-500': form.errors.product_id }"
                >
                  <option value="">Select Product</option>
                  <option v-for="product in products" :key="product.id" :value="product.id">
                    {{ product.name }} (Current Stock: {{ product.quantity }})
                  </option>
                </select>
                <div v-if="form.errors.product_id" class="text-red-500 text-sm mt-1">
                  {{ form.errors.product_id }}
                </div>
              </div>

              <div>
                <label for="type" class="form-label">Movement Type</label>
                <select
                  id="type"
                  v-model="form.type"
                  class="select-field"
                  :class="{ 'border-red-500': form.errors.type }"
                >
                  <option value="">Select Type</option>
                  <option v-for="(label, value) in types" :key="value" :value="value">
                    {{ label }}
                  </option>
                </select>
                <div v-if="form.errors.type" class="text-red-500 text-sm mt-1">
                  {{ form.errors.type }}
                </div>
              </div>

              <div>
                <label for="quantity" class="form-label">Quantity</label>
                <input
                  id="quantity"
                  v-model="form.quantity"
                  type="number"
                  min="1"
                  class="input-field"
                  :class="{ 'border-red-500': form.errors.quantity }"
                />
                <div v-if="form.errors.quantity" class="text-red-500 text-sm mt-1">
                  {{ form.errors.quantity }}
                </div>
              </div>

              <div>
                <label for="notes" class="form-label">Notes</label>
                <textarea
                  id="notes"
                  v-model="form.notes"
                  rows="3"
                  class="input-field"
                  :class="{ 'border-red-500': form.errors.notes }"
                  placeholder="Add any additional notes here..."
                ></textarea>
                <div v-if="form.errors.notes" class="text-red-500 text-sm mt-1">
                  {{ form.errors.notes }}
                </div>
              </div>

              <div class="flex justify-end space-x-4">
                <Link :href="route('stock-movements.index')" class="btn-secondary">Cancel</Link>
                <button type="submit" class="btn-primary" :disabled="form.processing">
                  {{ form.processing ? 'Recording...' : 'Record Movement' }}
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </AppLayout>
</template>

<script setup>
import { useForm, Link } from '@inertiajs/vue3'
import AppLayout from '@/Layouts/AppLayout.vue'

const props = defineProps({
  products: Array,
  types: Object,
})

const form = useForm({
  product_id: '',
  type: '',
  quantity: '',
  notes: '',
})

const submit = () => {
  form.post(route('stock-movements.store'))
}
</script>

<style scoped>
.form-label {
  @apply block text-sm font-medium text-gray-700;
}

.input-field {
  @apply mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50;
}

.select-field {
  @apply mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50;
}

.btn-primary {
  @apply inline-flex items-center px-4 py-2 bg-indigo-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-indigo-700 focus:outline-none focus:border-indigo-700 focus:ring ring-indigo-300 disabled:opacity-25 transition ease-in-out duration-150;
}

.btn-secondary {
  @apply inline-flex items-center px-4 py-2 bg-white border border-gray-300 rounded-md font-semibold text-xs text-gray-700 uppercase tracking-widest hover:bg-gray-50 focus:outline-none focus:border-indigo-300 focus:ring ring-indigo-200 disabled:opacity-25 transition ease-in-out duration-150;
}
</style>
